#!/bin/bash

version=$1
image="lucassousaweb/chatwoot"

echo "Building Chatwoot Docker Image - Version: $version"

docker images | grep $image | awk '{print $3}' | xargs -I {} docker rmi -f {}

docker build --no-cache -t $image:$version -f Dockerfile .
docker push $image:$version

